### ISSUE TITLE
Improve player movement during grapple

### ISSUE THREAD

**Issue by mathewajk** [lfdelta/PitGameMaker#3]
Experiment with gravity and player control during grapple; this may require implementing an acceleration or pseudo-force rather than directly setting the player velocity when grappling.

Maintain horizontal velocity after releasing the grapple, rather than coming to a dead stop mid-air.

**Comment by lfdelta** [comment]
We decided to remove nuanced mid-grapple mobility and implement a straightforward, linear-motion hookshot which cannot be ended prematurely.
